modLoader="javafml"
license="MIT"
loaderVersion="[36,)"
[[mods]]
modId="pocketstorage"
version="${file.jarVersion}"
displayName="Pocket Storage"
logoFile="logo.png"
credits=""
authors="Flanks255"
description='''
'''
