modLoader="javafml"
license="MIT"
loaderVersion="[44,)"
[[mods]]
modId="pocketstorage"
version="${file.jarVersion}"
displayName="Pocket Storage"
logoFile="logo.png"
credits=""
authors="Flanks255"
description='''
'''
[[dependencies.pocketstorage]]
modId="forge"
mandatory=true
versionRange="[44.0.0,)"
ordering="NONE"
side="BOTH"