modLoader="javafml"
license="MIT"
loaderVersion="[2,)"
[[mods]]
modId="pocketstorage"
version="${file.jarVersion}"
displayName="Pocket Storage"
logoFile="logo.png"
credits=""
authors="Flanks255"
description='''
'''
[[dependencies.pocketstorage]]
modId="neoforge"
required=true
versionRange="[20.4,)"
ordering="NONE"
side="BOTH"