modLoader="javafml"
loaderVersion="${loader_version}"
license="MIT"
issueTrackerURL="https://github.com/Flanks255/simplylight/issues"
[[mods]]
modId="pocketstorage"
version="${mod_version}"
displayName="Pocket Storage"
logoFile= "logo.png"
credits=""
authors="Flanks255"
description='''
'''
[[dependencies.pocketstorage]]
modId="neoforge"
required=true
versionRange="[20.6,)"
ordering="NONE"
side="BOTH"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"